version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: vuosikalenteri-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: vuosikalenteri
      POSTGRES_PASSWORD: vuosikalenteri123
      POSTGRES_DB: vuosikalenteri
    ports:
      - "5452:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
